feat(tLN/removeSubscriptionSupervision)
OpenEnergyTools/scl-lib pull request #38
Opened 2023-07-16 22:29 UTC by danyill

* Fix supervision function selector scoping (closes #6)
* Allow only CB or LN removal for subscription supervision removal (closes #18)

WIP, still to do:

* SV tests
* Tests `for canRemoveSubscriptionSupervision`

This breaks the previous API. Subscription removal only either removes the LN or the `textContent` of the `Val` element.
Additionally the first supervision in the data model cannot be removed (and trying only yields removal of the `textContent` of the `Val` element).

I'll complete this soon if this seems like the correct direction @JakobVogelsang

2023-07-19 18:46 UTC, danyill commented on index.ts
> +export { canRemoveSubscriptionSupervision } from "./tLN/canRemoveSubscriptionSupervision.js";
I guess we'll need to refactor this for adding supervisions with a similar function to check if we can create a supervision instance.

2023-07-28 14:58 UTC, JakobVogelsang commented on index.ts
> +export { canRemoveSubscriptionSupervision } from "./tLN/canRemoveSubscriptionSupervision.js";
Partly that is true. For the creation of a subscription, supervision I at the moment check for this:
- is SrcRef editable (that is the check we need here too)
- exist yet another `form` LGOS or LSVS that does pin the parent for those logical nodes in the subscriber IED (we do not need this check when we remove)
- whether a control block is already supervised in the subscriber IED (also not neccassary)

2023-07-28 15:22 UTC, JakobVogelsang commented on tLN/removeSubscriptionSupervision.ts
> +  options?: { removeLN: boolean }
I would like to add a default options object here. That read better and can be better handled in the function below like so:

`(..., options = {removeLN: false}): (Remove | Insert)[]`

2023-07-28 15:47 UTC, JakobVogelsang commented on tLN/canRemoveSubscriptionSupervision.ts
> +  const ln = supervisionElement?.closest("LN") ?? null;
I just see that is something I have introduced, sorry for this. But as you are touching it, I would love this to be removed. It reads better I think.

2023-07-28 15:49 UTC, JakobVogelsang commented on tLN/canRemoveSubscriptionSupervision.ts
> +/** @returns Whether `DA` with name `setSrcRef` can edited by SCL editor */
My spelling error I would love you to fix. `...setSrcRef can be edited`. I would in addition make the doc more precise and mention `DAI` as well like so: `Whether `DA` | `DAI`...`

2023-07-28 16:01 UTC, JakobVogelsang commented on tLN/canRemoveSubscriptionSupervision.ts
> +  extRefOrExtRefs: Element | Element[]
If you want to make this function available for users outside the `scl-lib` you need to either 
1. restrict the input to single `ExtRef` element or 
2. extend the signiture of the output to somethink like 
```ts
{
    canBeRemove: boolean,
    toBeRemoved: GroupedExtRefs
}
```

If you really need this function somewhere, I would be in favor of the second option. The first one will lead to mistakes on the user's side as soon as it is used somewhere in a loop/map.

2023-07-28 16:02 UTC, JakobVogelsang commented on tLN/canRemoveSubscriptionSupervision.ts
> +  if (!extRefOrExtRefs) return false;
Is that a scenario that need to be covered? This if-clause can never be reached. I wonder why the coveradge did not show this.

2023-07-28 16:03 UTC, JakobVogelsang commented on index.ts
> +import { canRemoveSubscriptionSupervision } from "./tLN/canRemoveSubscriptionSupervision.js";
This is exported twice here.

2023-07-28 16:07 UTC, JakobVogelsang commented on tExtRef/unsubscribe.spec.ts
> +    expect(isRemove(actions[3])).to.be.true;
I would not want to have two signatures to check for edit objects. So either you change both to:

`expect(isRemove(...)).to.be.true` or (my favourite) change all to
`expect(...).to.satisfy(isRemove)`

isRmove above stand for isInsert as well

2023-07-28 16:11 UTC, JakobVogelsang commented on tLN/canRemoveSubscriptionSupervision.spec.ts
> +        const extRef = docEd2Goose.querySelector(
You are testing exclusively with single ExtRefs. If you want to make this function available I would be in favour to have more somplex tests with ExtRef arrays in the test. I personally do not see this function useful outside of `removeSubscriptionSupervision` and would then not export it.

2023-07-28 16:25 UTC, JakobVogelsang commented on tLN/removeSubscriptionSupervision.ts
> +export function removeSubscriptionSupervision(
I am a pain in the ass with this PR. I am really sorry. This API as well does not really feel correct to me. I can imagine that users that want to remove subscription supervision are not intuitively having the ExtRef available. You know, I would rather think of something like this:

`removeSubscriptionSupervision(controlBlock: Element, subscriberIed: Element)`. This is still doing some useful things as the check for `valImport` and `valKind`. You could also think of having an option that allows you to define an array of ExtRefs to be checked against, like so:

```ts
RemoveSubscrptionSupervisionOptions = {
    /** Whether to only empty the Val text content */
    valOnly: boolean;
    /** ExtRef elements triggering this remove default [] means direct remove */
    pendingUnsubscription: Element[];
}
```
option: {valOnly: true, pendingUnsubscriptions: []}


I think that when someone is using this function, this person is knowing what to do. If not, it should be handled by the unsubscribe function.

2023-07-28 16:26 UTC, JakobVogelsang commented on tLN/removeSubscriptionSupervision.ts
> +  options?: { removeLN: boolean }
Obsolete, see comment the line above.

2023-07-28 16:29 UTC, JakobVogelsang requested changes
@danyill Your two points that you have formulated in the linked issues are very valid and those are covered here in well. I have a bit pain with the function exports. We need to talk through the API I think before you can proceed here.

2023-07-28 22:41 UTC, danyill commented on tLN/canRemoveSubscriptionSupervision.spec.ts
> +        const extRef = docEd2Goose.querySelector(
There are some tests with multiple ExtRefs

2023-07-28 22:42 UTC, danyill commented on tLN/canRemoveSubscriptionSupervision.ts
> +  extRefOrExtRefs: Element | Element[]
I'd like a function like this so I can show in a UI whether it is possible to remove a subscription supervision.

2023-07-28 22:43 UTC, danyill commented
Thank you for your review. If you agree, let's close this PR and agree the appropriate API and then perhaps code which may be of use from here can be transferred into a new, clean PR. 

I had, perhaps mistakenly thought since I was adding to tests to an already existing piece of code we had already agreed on this but I think that was not an appropriate assumption.

2023-07-31 20:30 UTC, JakobVogelsang commented
Let's close. Sorry for the additional effort, I am causing you.

2023-07-31 20:30 UTC, closed without merging