Improve test files schema validity and fix some order issues, part of #47
OpenEnergyTools/scl-lib pull request #48
Opened 2023-09-22 14:55 UTC by danyill

This resolves the easy part. More on what remains I will write on the issue.

2023-09-22 15:01 UTC, danyill commented on tIED/insertIED.ts
> +    reference: getReference(oldDataTypeTemplates, "EnumType"),
This is really the only thing to see here :wink:

2023-09-23 17:43 UTC, JakobVogelsang commented on tIED/insertIED.ts
> +    reference: getReference(oldDataTypeTemplates, "EnumType"),
Uff I am sorry! I did miss this as the order has been checked for and empty SCL! Great!

2023-09-23 17:49 UTC, JakobVogelsang commented on tIED/insertIED.spec.ts
> +    const secondIedImports = insertIed(scl, anotherValidIed);
I would be careful with this! The function `importIed` is not aiming to support multi IED import. We cannot give this promise. It is very likely that it will work this way, as handleEdit takes less time to do stuff compared to the constructing of the Edit[]. Still, to make this clear, I would love to leave tests doing multi IED import out of this function spec. 
There will be an `importIEDs` function exported. Initially I did try to have such a function but failed due to the complexity coming with it. 
For now I would ask you to have those tests be part of your repository and when the `importIEDs` function is available you can switch and remove those.

2023-09-23 17:50 UTC, JakobVogelsang commented on tIED/insertIED.spec.ts
> +    const secondIedImports = insertIed(scl, anotherValidIed);
Bwt. the regression test here can be done with a simple IED import by importing to and IED with existing `DOType` and an `EnumType` being copied over.

2023-09-23 17:51 UTC, JakobVogelsang commented on tIED/importIED/valid.iid
> +	<IED name="TestImportIED" type="TestType" manufacturer="TestMan" originalSclVersion="2007"
Those as automated formatting issues is that? Or are those changes needed to the tests?

2023-09-23 17:52 UTC, JakobVogelsang requested changes
@danyill I am sorry, but I have to request changes. Maybe I am too strict at the moment :(

2023-09-23 17:54 UTC, JakobVogelsang commented
One more thing: I would love to have one commit per issue. With this PR I have the impression this one fix and would expect one commit.

2023-09-23 19:16 UTC, danyill commented on tIED/importIED/valid.iid
> +	<IED name="TestImportIED" type="TestType" manufacturer="TestMan" originalSclVersion="2007"
Well, `NewThing` is schema invalid...

2023-09-23 19:16 UTC, danyill commented on tIED/insertIED.spec.ts
> +    const secondIedImports = insertIed(scl, anotherValidIed);
Sure, I'll adjust for that.

2023-09-23 19:25 UTC, danyill commented
I have made this PR more restricted. Far better to have some strict rules and order than a chaotic history. I must be a little more precise! :+1: 

My original concern was that the `valid.iid` was in fact, not schema valid making it difficult to sort out where the problem was for me but that should perhaps be dealt with separately.

And I forgot about the one commit per issue in the repo, I am sorry :disappointed:

2023-09-23 22:42 UTC, JakobVogelsang commented
LGTM thank you!!

two little thing I would ask you to change:

1 rename the commit to stick with conventional commit syntax. fix(importIED): ...
2 the name of the doc in the test you have touched could be changed to. That would read better I think

2023-09-23 23:38 UTC, danyill commented
> LGTM thank you!!
> 
> two little thing I would ask you to change:
> 
> 1 rename the commit to stick with conventional commit syntax. fix(importIED): ... 2 the name of the doc in the test you have touched could be changed to. That would read better I think

Quite right, done!

2023-09-24 14:53 UTC, JakobVogelsang approved these changes
LGTM

2023-09-24 14:53 UTC, merged