feat(tControl): function for looking up communications address
OpenEnergyTools/scl-lib pull request #56
Opened 2023-10-04 22:41 UTC by danyill

Closes #41

2023-10-08 19:32 UTC, JakobVogelsang requested changes
The functionality looks very good very good. Thank you for the good tests!!!
Two things I would like to have changed:
- I think we need more edge cases covered. I would at least expect that orphan control blocks are covered. That is not an unlikely scenario.
- the name of the function is not very descriptive. Maybe a refining session would make sence.

2023-10-08 19:32 UTC, JakobVogelsang commented on index.ts
> +export { getCommAddress } from "./tControl/getCommAddress.js";
I am not sure if the name of the function is very descriptive. I would have expected that there is some sort of `controlBlock` included. Something like:
- controlBlockCommunicationParameters
- contrlolBlockCommunicationAddress

2023-10-08 19:32 UTC, JakobVogelsang commented on index.ts
> +export { getCommAddress } from "./tControl/getCommAddress.js";
or event more prices like 

- controlBlockGseOrSmvAddress

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.ts
> +  const ctrlLdInst = ctrlBlock.closest('LDevice')!.getAttribute('inst');
I would propose to get an early return for orphan control blocks. In this line an error for such things would be the result.

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.ts
> +  if (serverAts.length > 0) {
Is that really necessary. I think if you process serverAts with a map it would be more readable.

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.ts
> +  const iedName = ied.getAttribute('name');
I found that function where all the data that is neccassery collected at the beginning are more readable. So

```ts

// collected all data
iedName = ...
ldInst = ...
ied = ...

...
if(!iedName || !ied || !apNames) return null

...

```

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.ts
> +function crossProduct<T>(...arrays: T[][]): T[][] {
Not sure about that, but I would have that rather in the utils file. It does make it more readable and for later contributors makes it easier to find it.

2023-10-08 19:32 UTC, JakobVogelsang commented on index.ts
> +export { getCommAddress } from "./tControl/getCommAddress.js";
I just see that the return is either `GSE` or `SMV`. So maybe `controlBlocksGseOrSvm`. Although the proposals not close to SCL syntax would work for me as well.

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.spec.ts
> +    expect(gseControl).to.not.equal(null);
chia offers `expect(...).to.not.be.null`

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.spec.ts
> +  it("returns a GSE for a GSEControl with the correct AP with no ServerAts defined", () => {
Test missing with orphan `GSEControl` or `SampledValueControl`

2023-10-08 19:32 UTC, JakobVogelsang commented on tControl/getCommAddress.spec.ts
> +  it("returns a GSE for a GSEControl referenced with ServerAt", () => {
Love those!

2023-10-09 20:52 UTC, danyill commented on tControl/getCommAddress.ts
> +  const ctrlLdInst = ctrlBlock.closest('LDevice')!.getAttribute('inst');
Why would we need to cover orphan control blocks? Shouldn't we make some assumptions about our documents, e.g. they are schema valid?

2023-10-09 20:56 UTC, danyill commented on tControl/getCommAddress.ts
> +  const ctrlLdInst = ctrlBlock.closest('LDevice')!.getAttribute('inst');
I'll add it I guess it makes it more robust for weird cases but I'm not sure when to do this and when not to (i.e. how to avoid making pathological assumptions about the document).

2023-10-09 20:57 UTC, danyill commented on tControl/getCommAddress.spec.ts
> +    expect(gseControl).to.not.equal(null);
Oh that is nicer, thanks

2023-10-09 21:08 UTC, danyill commented on tControl/getCommAddress.spec.ts
> +  it("returns a GSE for a GSEControl with the correct AP with no ServerAts defined", () => {
I will add that although I am unsure in what circumstances orphan control blocks can occur. I guess during some manipulation or creation in our code (as opposed to in a file?). Anyway for a little restructuring it seems like a good idea.

2023-10-09 21:12 UTC, danyill commented
Thank you for this review, I have endeavoured to make some improvements and taken your suggestion for the function name. I'm not entirely sure when we use `get` or `find` or when we drop the verb entirely...

2023-10-10 14:59 UTC, JakobVogelsang requested changes
LGTM aside one little name conflict. Thank you for the changes and for your patience.

2023-10-10 14:59 UTC, JakobVogelsang commented on index.ts
> +export { controlBlockGseOrSmv as getCommAddress } from "./tControl/controlBlockGseOrSmv.js";
I think this came automatically with a rename. Right or was it your intention?

2023-10-10 16:09 UTC, danyill commented on index.ts
> +export { controlBlockGseOrSmv as getCommAddress } from "./tControl/controlBlockGseOrSmv.js";
Quite right, fixed. Thanks for checking.

2023-10-10 18:06 UTC, JakobVogelsang requested changes
Still the same issue

2023-10-10 18:06 UTC, JakobVogelsang commented on index.ts
> +export { controlBlockGseOrSmv as getCommAddress } from "./tControl/controlBlockGseOrSmv.js";
Still there nothing changed here

2023-10-10 18:30 UTC, JakobVogelsang approved these changes
LGTM

2023-10-10 18:30 UTC, merged