feat(tLN): instantiate subscription supervision
OpenEnergyTools/scl-lib pull request #61
Opened 2023-10-19 22:12 UTC by JakobVogelsang

Closes #20

2023-12-26 06:33 UTC, danyill commented
Finally I am looking at this :tada:

2023-12-29 00:59 UTC, danyill requested changes
This is quite a large PR and I'm sorry I have not reviewed it in a timely manner :disappointed: . I appreciate your patience and this opportunity. :+1: :love_letter: 

This looks really good -- it is a surprisingly complex thing we are trying to do and it is very good to have it abstracted into `scl-lib`.

There seems to be just one issue - in that the supervision node is not always placed correctly - the rest are mostly questions and style comments. I have not carefully looked through the tests.

I have done a little test integration into oscd-supervision and it is looking good for the specific function we have here.

I did a little check on what we still need for supervisions to allow me to fully abstract out for oscd-supervision, oscd-subscriber-later-binding and oscd-subscriber-lb-*.

Here is the list I made:

* Add instantiation to `subscribe` function. Ideally when adding this, we would also have a `SubscribeOption` of `ignoreSupervision` (as we do for `unsubscribe`).
* https://github.com/OpenEnergyTools/scl-lib/issues/18
* Resolve https://github.com/OpenEnergyTools/scl-lib/issues/6
* Allow separate instantiation of a supervision element as per https://github.com/OpenEnergyTools/scl-lib/issues/20 (and fix the way we do deleting) and also provide an ability to check just "Can I instantiate a supervision LNode without necessary wanting to connect to a control block" which our current API does not allow.

I'm happy to do some of these but don't wish to interrupt your flow on this great work.

2024-01-01 22:45 UTC, JakobVogelsang commented on tLN/supervision/foundation.ts
> +/** Clojure returning unique inst attribute over for multiple subscriber IEDs */
Thank you will do :)

2024-01-01 22:46 UTC, JakobVogelsang commented on tLN/supervision/foundation.ts
> +    return lnInstGenerators.get(id)!(lnClass);
True thx

2024-01-01 23:45 UTC, JakobVogelsang commented on tLN/supervision/createSupervisionEdit.ts
> +      ?.nextElementSibling || getReference(parent, "LN");
You are right I would still not want to get rid of the fallback and would instead propose to re-write as follows:

```ts
...
const lastSupervisionLn = parent.querySelector(`:scope > LN[lnClass="${lnClass}"]:last-child`)
const reference = lastSupervisionLn ? lastSupervisionLn.nextElementSibling : getReference(parent, "LN").
```

What do you say about this proposal @danyill ?

2024-01-02 08:17 UTC, danyill commented on tLN/supervision/createSupervisionEdit.ts
> +      ?.nextElementSibling || getReference(parent, "LN");
Unless I err it still doesn't seem right:

So within an LDevice, we might have the following cases:

**Case 1:**

```
LN0
LN[lnClass="??1"]
LN[lnClass="LGOS"] <insert after this one>
LN[lnClass="??2"]
```

**Case 2:**

```
LN0
LN[lnClass="??1"]
LN[lnClass="LGOS"] <insert after this one>
AccessControl
```

**Case 3:**
```
LN0
LN[lnClass="??1"]
LN[lnClass="LGOS"] <insert after this one>
```

**Case 4:**
```
LN0 <insert after this one>
```

**Case 5:**
```
LN0 <insert after this one>
AccessControl
```

We want to add after the last `LGOS`, which may be the last element if there is no `AccessControl`.

- Case 1 and Case 2 are dealt with in the existing code.
- Case 3 must be handled by passing null (i.e. add to the end of the parent).
- Case 4 and 5 should be handled with `getReference`

Your proposal doesn't handle Case 3 I think (where we would insert between `LN0` and the first `LN`).

How about something like:

```suggestion
const lastSupervisionLn = parent.querySelector(`:scope > LN[lnClass="${lnClass}"]:last-child`)
let reference

if (lastSupervisionLn) {
  reference = lastSupervisionLn.nextElementSibling ? lastSupervisionLn.nextElementSibling : null;
} else  {
  reference = getReference(parent, "LN")
}
```

2024-01-02 10:57 UTC, JakobVogelsang commented on tLN/supervision/createSupervisionEdit.ts
> +      ?.nextElementSibling || getReference(parent, "LN");
The property `nextElementSibling` returns `null` when the element is the last element [nextElementsSibling](https://developer.mozilla.org/en-US/docs/Web/API/Element/nextElementSibling). As such, the line 139 can be reduced to `reference = lastSupervision.nextElementSibling` and then I think we are down to:
1. If there is a `lastSupervisionLn` pick the `nextElementSibling` (including the option there is no in which case we return null)
2. there is no such thing as `lastSupervisionLn` and we then let `getReference` figure out the correct next element sibling.

2024-01-02 10:58 UTC, JakobVogelsang commented on tLN/supervision/createSupervisionEdit.ts
> +      ?.nextElementSibling || getReference(parent, "LN");
And then I think the two-liner that I proposed should be enough. The name `lstSupervisionLn` is maybe a bit strange.

2024-01-02 17:48 UTC, danyill commented on tLN/supervision/createSupervisionEdit.ts
> +      ?.nextElementSibling || getReference(parent, "LN");
You are quite correct, thanks for the discussion :+1: I think `lastSupervisionLn` is fine

2024-01-02 21:08 UTC, JakobVogelsang commented on tLN/supervision/createSupervisionEdit.ts
> +function createSupervisionLogicalNode(
I would love to make it a separate PR. Would that be ok with you?

2024-01-02 21:41 UTC, JakobVogelsang commented on tLN/supervision/createSupervisionEdit.ts
> +      .filter((ln) => !userSupervisions?.has(ln))
The function can deal with multiple subscription supervisions at once. In these cases you need to save what supervisions have been set. The filter and the Set is filtering this.

2024-01-02 23:03 UTC, JakobVogelsang commented on tLN/supervision/canInstantiateSubscriptionSupervision.ts
>      availableSupervisorSpots.length > 0
Very true thank you!

2024-01-02 23:42 UTC, JakobVogelsang commented
@danyill When this PR is in there is no running work and as such I would love if you would do some polishing.

2024-01-04 00:28 UTC, danyill commented
Thank you for making these changes.

It looks good to me with the exception that we've lost a bit of code coverage by not testing the insertion order fallback:

![image](https://github.com/OpenEnergyTools/scl-lib/assets/674783/339f29c6-d87b-4bcc-b1fb-ce632458675b)

2024-01-04 00:28 UTC, danyill approved these changes

2024-01-04 21:39 UTC, merged