feat(tLN): removeSupervision
OpenEnergyTools/scl-lib pull request #84
Opened 2024-01-30 22:07 UTC by JakobVogelsang

Closes #18 

I did create a new function as the name does more explain the function. Compared to `removeSubscriptionSupervision` here no supervision of a subscription is removed but rather the supervision directly. The two options allow to configure the function to individual needs.

@danyill I would be happy for a review.

2024-02-01 18:44 UTC, danyill requested changes
Thank you for this and also for the opportunity to review this PR.

I think it would be good to ensure we could remove a supervision node whether or not there is a `Val` element and also that removing a supervision node should not depend on having a specific `Private`.

Happy to discuss!

2024-02-01 18:44 UTC, danyill commented on tLN/supervision/removeSupervision.ts
> +  if (!val) return null;
Should we re-order this. Even if there is no `Val` element I think I should be able to use `removeSupervisionLn`.

2024-02-01 18:44 UTC, danyill commented on tLN/supervision/removeSupervision.ts
> +    return { node: supervisionLn };
I think we should not require the `OpenSCD.create` private before allowing removal.

It seems to me that IEC 61850-7-1 Ed 2.1 talks specifically about "capabilities description provided by the ICT in order that the SCT can add/delete or not LGOS/LSVS supervision logical nodes" in Annex G, section G.1 General.

I think this means if we pass the `canRemoveSupervision` test we can either change the Val  text content or add/remove supervision instances completely.

And if I'm wrong I think we should leave this up to the user and not restrict it to our private type.

2024-02-01 18:44 UTC, danyill commented on tLN/supervision/removeSupervision.ts
> +    ':scope > DOI > DAI[name="setSrcRef"] > Val',
Oh my favourite! We must scope that DOI a little more tightly :stuck_out_tongue_winking_eye: to either:

`DOI[name="GoCBRef"]` or `DOI[name="SvCBRef"]`

2024-02-01 19:20 UTC, danyill commented on tLN/supervision/removeSupervision.ts
> +    return { node: supervisionLn };
Oh yes, and also this bit:

![image](https://github.com/OpenEnergyTools/scl-lib/assets/674783/18013b94-6bae-4c73-86a0-d9fb0074faed)

2024-02-07 21:16 UTC, JakobVogelsang commented on tLN/supervision/removeSupervision.ts
> +    return { node: supervisionLn };
I think I get now what you were about. I agree. I would want to change that as well in the other remove function and per default remove only the val element.

2024-02-07 21:17 UTC, JakobVogelsang commented on tLN/supervision/removeSupervision.ts
> +    ':scope > DOI > DAI[name="setSrcRef"] > Val',
So true :)

2024-02-10 21:33 UTC, danyill approved these changes
LGTM, thank you for incorporating this feedback.

2024-02-10 22:43 UTC, merged