feat(tIED): allow IED removal (closes #91).
OpenEnergyTools/scl-lib pull request #92
Opened 2024-03-29 23:54 UTC by danyill

Closes #91

2024-03-30 00:23 UTC, danyill commented
Currently, this does not remove empty SubNetwork elements if we are removing the last ConnectedAP.

I guess we could do something like the following but I worry about over-reach. And I guess we could make it an option. Perhaps we could just wait until it's a problem for someone :wink: 

```js
function removeWithIedName(ied: Element, iedName: string): Remove[] {
  const selector = elementsToRemove
    .map((iedNameElement) => `${iedNameElement}[iedName="${iedName}"]`)
    .join(",");

  return Array.from(ied.ownerDocument.querySelectorAll(selector))
    .filter(isPublic)
    .map((element) => {
      if (
        element.tagName === "ConnectedAP" &&
        element.parentElement!.querySelectorAll("ConnectedAP").length === 1
      ) {
        return { node: <Element>element.parentElement };
      }
      return { node: element };
    });
}
```

2024-03-30 03:30 UTC, JakobVogelsang commented on tIED/removeIED.ts
> +    !(<Element>remove.node).hasAttribute("name")
Would you be so nice and change to `(remove.node as Element).hasAttribute("name")`. Just for consistency reasons.

2024-03-30 03:31 UTC, JakobVogelsang commented on tIED/removeIED.ts
> +      return { element, attributes: { iedName: "None" } };
Should the `ldInst` be set to null as well?

2024-03-30 03:32 UTC, JakobVogelsang commented on tIED/removeIED.ts
> +      (ied) => ied.hasAttribute("name") && ied.getAttribute("name") !== iedName
I think `ied.getAttribute("name") === iedName` should be enough. You know iedName is not null.

2024-03-30 03:34 UTC, JakobVogelsang commented on tIED/removeIED.ts
> +  "IEDName",
That has no effect, right. `IEDName` has IED.name in textContent

2024-03-30 03:36 UTC, JakobVogelsang requested changes
That was a pleasure to review. Thank you. Well structure and nice tests. There are just very minor issue that I have spotted.

2024-03-30 03:38 UTC, JakobVogelsang commented
I think an issue marking the fact that the `removeIed` does not clean the `DataTypeTemplates` section would also be nice. I don't think we should have that from the beginning, but a reminder is nice to have.

2024-03-30 05:27 UTC, danyill commented on tIED/removeIED.ts
> +      return { element, attributes: { iedName: "None" } };
I don't know. Couldn't that be used for specification? If I had a virtual IED and I was swapping virtual IEDs, might I want to retain the `ldInst`?

2024-03-30 05:28 UTC, danyill commented on tIED/removeIED.ts
> +      (ied) => ied.hasAttribute("name") && ied.getAttribute("name") !== iedName
Quite correct.

2024-03-30 05:28 UTC, danyill commented on tIED/removeIED.ts
> +  "IEDName",
Good spotting.

2024-03-30 05:31 UTC, danyill commented on tIED/removeIED.ts
> +      return { element, attributes: { iedName: "None" } };
Well for now, let's remove it and see if it's a cause of trouble. It's a bit unclear to me what the valid combinations are here.

2024-04-01 09:30 UTC, danyill commented
Thank you for this review, I have made some updates.

2024-04-01 21:25 UTC, merged